apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-nfs
  namespace: monitoring
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.10.87            
    path: "/mnt/user/grafana" 
    readOnly: false