[GLOBAL]
pants_version = '2.15.0'

backend_packages = [
  "pants.backend.shell",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.docker",
  "pants.backend.build_files.fmt.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.shell.lint.shellcheck"
]


[anonymous-telemetry]
enabled = false

[docker]
executable_search_paths = [
    "/usr/local/bin",
]
